name = "TethysChlorisCore"
uuid = "c22758e7-e854-5bdb-8df2-7602c47a9d98"
authors = ["Hugo Solleder <hugo.solleder@epfl.ch>"]
version = "0.2.0"

[deps]
BracketingNonlinearSolve = "70df07ce-3d50-431d-a3e7-ca6ddb60ac1e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"

[compat]
BracketingNonlinearSolve = "1.5.0"
NCDatasets = "0.14"
SciMLBase = "2.122.1"
SimpleNonlinearSolve = "2.9.0"
julia = "1.10"
