name = "TethysChlorisCore"
uuid = "c22758e7-e854-5bdb-8df2-7602c47a9d98"
authors = ["Hugo Solleder <hugo.solleder@epfl.ch>"]
version = "0.2.0"

[deps]
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[compat]
NCDatasets = "0.14"
julia = "1.10"
